### ISSUE TITLE
Fetch all accounts limited to 25

### ISSUE THREAD

**Issue by mhoskiso** [cte/facebook-ruby-ads-sdk#4]
I'm unable to retrieve more than 25 accounts. Needs an option to paginate.

**Comment by mhoskiso** [comment]
I've added query[:limit] ||= 200 to get for now.

**Comment by cte** [comment]
Thanks for the heads up. Will fix shortly.

**Comment by cte** [comment]
This should do it: cdcc32d4efb843943775dd338468ba6b15e5f912
