### ISSUE TITLE
API version error

### ISSUE THREAD

**Issue by aacook** [cte/facebook-ruby-ads-sdk#6]
I created a new app in Facebook recently and it set the API version to 2.9. Up until now, my testing app was using 2.8 and everything is working great.

But, when I try a token from the new app (my staging environment), I get this error:
You are calling a deprecated version of the Ads API. Please update to the latest version: v2.9

It looks like the version number isn't editable in the app settings. https://www.dropbox.com/s/jze2o5125e2mw84/Screenshot%202017-04-21%2017.00.16.png?dl=0

Is there a way to set the API version number in facebook_ads?

**Comment by cte** [comment]
I'll upgrade to 2.9 soon. Not sure if it makes sense to make the version number configurable since some things likely won't work with older versions, and new versions often introduce breaking changes.

**Comment by aacook** [comment]
Ah yeah, makes sense. Didn't realize Facebook just released 2.9 just a couple days ago. 
([https://developers.facebook.com/ads/blog/post/2017/04/18/marketing-API-2.9](https://developers.facebook.com/ads/blog/post/2017/04/18/marketing-API-2.9))

Thanks for building this sdk, it's awesome.

**Comment by cte** [comment]
Here's a way to change the API version: https://github.com/cte/facebook-ruby-ads-sdk/commit/335047b263c9bc760ed770f3caf8c70add93f385
